### ISSUE TITLE
Unkown attribute " passwordToggleEnabled " 

### ISSUE THREAD

**Issue by harishsg** [googlesamples/android-NavigationDrawer#13]
Unknown attribute is " passwordToggleEnabled " is not supporting eventhough i replaced the package xmlns:app="http://schemas.android.com/apk/res-auto" with chesbank.

and still its showing the same error like " Unknown attribute is " passwordToggleEnabled " "

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
