### ISSUE TITLE
Not updated for Material

### ISSUE THREAD

**Issue by busches** [googlesamples/android-NavigationDrawer#4]
The navigation drawer is still using the ICS style and not the new Navigation Drawer pattern (http://www.google.com/design/spec/patterns/navigation-drawer.html) that covers the action bar, it would be great if it was updated, as there appears to be zero working examples of that.

**Comment by surfer190** [comment]
@busches Also functionality for sliding over the `actionBar` is not implemented

**Comment by tjohns** [comment]
Indeed. We need to update this sample to follow the latest UX standards.

**Comment by IgorGanapolsky** [comment]
Will this be updated any time soon?  I'd love to learn the latest Material practices in this sample.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
