### ISSUE TITLE
Still using ActionBar!

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-NavigationDrawer#5]
Your sample uses ActionBar and ActionBarDrawerToggle().  That makes no sense.  I would like it to extend `AppCompatActivity` and use a Toolbar.  Please advise.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
